JUDGE0_API_KEY=
JUDGE0_API_HOST=0.0.0.0
JUDGE0_API_PORT=2358
POSTGRES_HOST=db
POSTGRES_DB=judge0
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
REDIS_HOST=redis
REDIS_PORT=6379
RACK_ENV=production
WAIT_FOR_DB_TIMEOUT=10
JUDGE0_ENABLE_WAIT_RESULT=true
JUDGE0_ALLOW_ORIGIN='*'
