import Head from "next/head";
import React from "react";
import { Header } from "../Header";
import { MainContainer } from "../MainContainer";

interface MainLayoutProps {
	children: React.ReactElement;
}

export const MainLayout = ({ children }: MainLayoutProps) => {
	return (
		<>
			<Head>
				<title>Code check</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<MainContainer>
				<Header />
			</MainContainer>
			<main>{children}</main>
		</>
	);
};
